# Generated by Django 3.1.4 on 2021-01-27 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=128, unique=True)),
                ('app_name', models.CharField(max_length=64)),
                ('playstore_link', models.URLField()),
                ('app_description', models.TextField()),
                ('app_summary', models.TextField()),
                ('play_store_genre', models.CharField(max_length=32)),
                ('min_installs', models.PositiveIntegerField()),
                ('avg_rating', models.FloatField()),
                ('ratings_count', models.PositiveIntegerField()),
                ('reviews_count', models.PositiveIntegerField()),
                ('free', models.BooleanField()),
                ('icon_link', models.URLField()),
                ('header_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='QueryOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlgSiteReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Anonymous User', max_length=64)),
                ('email_id', models.EmailField(max_length=256)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=256, unique=True)),
                ('option_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='option_1', to='api.queryoption')),
                ('option_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='option_2', to='api.queryoption')),
                ('option_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='option_3', to='api.queryoption')),
                ('option_4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='option_4', to='api.queryoption')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.app')),
                ('general_choice_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_choice_1', to='api.queryoption')),
                ('general_choice_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_choice_2', to='api.queryoption')),
                ('general_query_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_query_1', to='api.reviewquery')),
                ('general_query_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_query_2', to='api.reviewquery')),
                ('genre_choice_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genre_choice_1', to='api.queryoption')),
                ('genre_choice_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genre_choice_2', to='api.queryoption')),
                ('genre_choice_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genre_choice_3', to='api.queryoption')),
                ('genre_choice_4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genre_choice_4', to='api.queryoption')),
                ('genre_query_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genre_query_1', to='api.reviewquery')),
                ('genre_query_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genre_query_2', to='api.reviewquery')),
                ('genre_query_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genre_query_3', to='api.reviewquery')),
                ('genre_query_4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genre_query_4', to='api.reviewquery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayStoreReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Anonymous User', max_length=64)),
                ('user_img_link', models.URLField()),
                ('content', models.TextField()),
                ('rating', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('up_vote_count', models.PositiveIntegerField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.app')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=32, unique=True)),
                ('apps', models.ManyToManyField(to='api.App')),
                ('query_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='query_1', to='api.reviewquery')),
                ('query_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='query_2', to='api.reviewquery')),
                ('query_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='query_3', to='api.reviewquery')),
                ('query_4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='query_4', to='api.reviewquery')),
            ],
        ),
    ]
