# Generated by Django 3.1.4 on 2021-05-16 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=128, unique=True)),
                ('app_name', models.CharField(max_length=128)),
                ('app_summary', models.CharField(max_length=256)),
                ('min_installs', models.PositiveIntegerField()),
                ('avg_rating', models.FloatField()),
                ('ratings_count', models.PositiveIntegerField()),
                ('reviews_count', models.PositiveIntegerField()),
                ('free', models.BooleanField()),
                ('icon_link', models.URLField()),
                ('similar_apps', models.ManyToManyField(blank=True, related_name='_app_similar_apps_+', to='api.App')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.query')),
            ],
        ),
        migrations.CreateModel(
            name='SlgSiteReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=128)),
                ('email_id', models.EmailField(max_length=256)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('city', models.CharField(max_length=128)),
                ('up_votes', models.PositiveIntegerField(blank=True, default=1)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.app')),
                ('query_choices', models.ManyToManyField(blank=True, to='api.QueryChoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=128, unique=True)),
                ('apps', models.ManyToManyField(blank=True, to='api.App')),
                ('queries', models.ManyToManyField(blank=True, to='api.Query')),
            ],
        ),
    ]
