# Generated by Django 3.1.4 on 2021-05-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='city',
            field=models.CharField(default='not available', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='up_votes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
