# Generated by Django 3.1.4 on 2021-01-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20210130_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
