# Generated by Django 3.1.4 on 2021-05-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210522_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slg_user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
