# Generated by Django 3.1.4 on 2021-05-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210523_0014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SLG_User',
        ),
    ]
