# Generated by Django 3.1.4 on 2021-05-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210522_2314'),
        ('api', '0009_slg_user'),
    ]

    operations = [
    ]
