# Generated by Django 3.1.4 on 2021-05-22 20:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_slg_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SLG_User',
            new_name='SlgUser',
        ),
    ]
