# Generated by Django 3.1.4 on 2021-05-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210523_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slguser',
            name='date_created',
        ),
    ]
