# Generated by Django 3.1.4 on 2021-08-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_slguser_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slguser',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='slguser',
            name='profile_pic_url',
            field=models.TextField(null=True),
        ),
    ]
