# Generated by Django 3.1.4 on 2021-07-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_review_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlgSiteReview',
        ),
    ]
