# Generated by Django 3.1.4 on 2020-12-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=128, unique=True)),
                ('app_name', models.CharField(max_length=64)),
                ('playstore_link', models.URLField()),
                ('installs_count', models.PositiveIntegerField()),
                ('avg_rating', models.FloatField()),
                ('ratings_count', models.IntegerField()),
                ('reviews_count', models.IntegerField()),
                ('is_free', models.BooleanField()),
                ('app_size', models.CharField(max_length=8)),
                ('genre', models.CharField(max_length=32)),
                ('icon_link', models.URLField()),
                ('header_link', models.URLField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
