# Generated by Django 3.1.4 on 2021-01-30 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
        ('api', '0002_auto_20210127_1754'),
    ]

    operations = [
    ]
