# Generated by Django 3.1.4 on 2021-01-06 16:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20210104_0223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='AppReview',
        ),
    ]
