# Generated by Django 3.1.4 on 2021-01-23 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_slgusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slgusers',
            name='app_id',
            field=models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='api.app'),
        ),
    ]
