# Generated by Django 3.1.4 on 2021-01-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210106_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appreview',
            name='props',
        ),
        migrations.RemoveField(
            model_name='appreview',
            name='user',
        ),
        migrations.AddField(
            model_name='appreview',
            name='genre',
            field=models.CharField(default='base', max_length=100),
        ),
    ]
