# Generated by Django 3.1.4 on 2021-01-23 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210123_1008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlgUsers',
            new_name='SlgUser',
        ),
    ]
