# Generated by Django 3.1.4 on 2021-01-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210115_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAppReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('genre', models.CharField(default='base', max_length=100)),
            ],
        ),
    ]
