# Generated by Django 3.1.6 on 2021-03-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210127_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_category_name', models.CharField(max_length=128, unique=True)),
                ('query_1', models.CharField(max_length=128, unique=True)),
                ('query_2', models.CharField(max_length=128, unique=True)),
                ('query_3', models.CharField(max_length=128, unique=True)),
                ('query_4', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
