name: Django Tests

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        env:
            DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
            HEROKU_POSTGRES_DB_URL: ${{ secrets.HEROKU_POSTGRES_DB_URL }}
            HEROKU_POSTGRES_DB_HOST: ${{ secrets.HEROKU_POSTGRES_DB_HOST }}
            HEROKU_POSTGRES_DB_NAME: ${{ secrets.HEROKU_POSTGRES_DB_NAME }}
            HEROKU_POSTGRES_DB_PWD: ${{ secrets.HEROKU_POSTGRES_DB_PWD }}
            HEROKU_POSTGRES_DB_USER: ${{ secrets.HEROKU_POSTGRES_DB_USER }}
            SLACK_NEW_APPS_CHANNEL_ID: ${{ secrets.SLACK_NEW_APPS_CHANNEL_ID }}
            SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_TOKEN }}
            SLACK_SITE_REVIEWS_CHANNEL_ID: ${{ secrets.SLACK_SITE_REVIEWS_CHANNEL_ID }}
            SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: ${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET }}
            SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: ${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY }}
        strategy:
            max-parallel: 4
            matrix:
                python-version: [3.7, 3.8, 3.9]
                os: [ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run Tests
              run: |
                  python manage.py test
